version: "3.7"

services:
  flask_auth_api:
    build:
      context: ../../auth_api/flask_app
      dockerfile: Dockerfile
    container_name: flask_auth_api
    env_file:
      - auth.env
    ports:
      - "5000:5000"
    volumes:
      - ../../auth_api/flask_app:/auth_api/flask_app
    networks:
      - movies_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - postgres_auth_test
      - redis_auth_test

  postgres_auth_test:
    image: postgres:13-alpine
    container_name: postgres_auth_test
    volumes:
      - ./pgdata2:/var/lib/postgresql/data
    env_file:
      - db_auth.env
    ports:
      - "5432:5432"
    networks:
      - movies_network

  redis_auth_test:
    build:
      context: ../../auth_api/redis_auth
      dockerfile: Dockerfile
    container_name: redis_auth_test
    ports:
      - "6379:6379"
    volumes:
      - ../../auth_api/redis_auth/conf/etc:/usr/local/etc/redis
    networks:
      - movies_network
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  tests:
    container_name: auth_api_test
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - flask_auth_api
    env_file:
        - tests.env
    networks:
      - movies_network
    command: ["bash", "-c", "PYTHONPATH=. python utils/wait_for_api.py && pytest -s src/"]


networks:
  movies_network:
